# Generated by Django 5.2.5 on 2025-09-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='სათაური')),
                ('text', models.TextField(verbose_name='ტექსი')),
                ('active', models.BooleanField(default=True, verbose_name='აქტიურია')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნის თარიღი')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი')),
                ('website', models.URLField(null=True, verbose_name='ვებ მისამართი')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['title'],
                'unique_together': {('title', 'text')},
            },
        ),
    ]
