# Generated by Django 5.2.5 on 2025-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_document_blogpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='blog_document/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='blog_picture/'),
        ),
    ]
