# Generated by Django 5.2.5 on 2025-09-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_picture_blogpostimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, verbose_name='მეილი')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='წაშლილია'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.author', verbose_name='ავტორები'),
        ),
    ]
