# Generated by Django 5.2.5 on 2025-09-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='დაბადების თარიღი'),
        ),
    ]
