# Generated by Django 5.2.5 on 2025-09-05 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpostcover'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostAuthorThroughTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Authors')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='BlogPost')),
            ],
            options={
                'verbose_name': 'Blog Post author through table',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authors_2',
            field=models.ManyToManyField(related_name='blog_posts_2', through='blog.BlogPostAuthorThroughTable', to='blog.author', verbose_name='Authors 2'),
        ),
    ]
