# Generated by Django 5.2.5 on 2025-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['title'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='document',
            field=models.FileField(null=True, upload_to='blog_post_documents/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='აქტიურია'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(null=True, upload_to='blog_post_picture/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.URLField(null=True, verbose_name='ვებ მისამართი'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('title', 'text')},
        ),
    ]
