# Generated by Django 5.2.5 on 2025-09-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_blogpost_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_post_covers/', verbose_name='Image')),
                ('blog_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='blog.blogpost', verbose_name='Blog Post')),
            ],
            options={
                'verbose_name': 'Blog Post Cover',
                'verbose_name_plural': 'Blog Post Covers',
            },
        ),
    ]
